AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AsgSchedulerApp

  Sample SAM Template for AsgSchedulerApp

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - DEV
      - PROD

Resources:
  AsgSchedulerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AsgSchedulerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudwatch:ListMetrics
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:Describe*
                  - autoscaling:*
                Resource: '*'
      RoleName: !Sub AsgSchedulerFunctionRole_${Environment}

  AsgSchedulerEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AsgSchedulerEventBridgePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:AsgSchedulerFunction_${Environment}:*"
                  - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:AsgSchedulerFunction_${Environment}"
      RoleName: !Sub AsgSchedulerEventBridgeRole_${Environment}

  AsgSchedulerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: AsgScheduler/
      Role: !GetAtt AsgSchedulerFunctionRole.Arn
      FunctionName: !Sub AsgSchedulerFunction_${Environment}
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        ScheduleStart:
          Type: ScheduleV2
          Properties:
            Name: !Sub AsgSchedulerStart_${Environment}
            Description: Daily schedule to invoke AsgSchedulerFunction for starting dev ASGs
            RoleArn: !GetAtt AsgSchedulerEventBridgeRole.Arn
            ScheduleExpression: "cron(0 8 ? * MON-FRI *)"
            ScheduleExpressionTimezone: "America/New_York"
            RetryPolicy:
              MaximumRetryAttempts: 5
              MaximumEventAgeInSeconds: 900
        ScheduleStop:
          Type: ScheduleV2
          Properties:
            Name: !Sub AsgSchedulerStop_${Environment}
            Description: Daily schedule to invoke AsgSchedulerFunction for stopping dev ASGs
            RoleArn: !GetAtt AsgSchedulerEventBridgeRole.Arn
            ScheduleExpression: "cron(0 18 ? * MON-FRI *)"
            ScheduleExpressionTimezone: "America/New_York"
            RetryPolicy:
              MaximumRetryAttempts: 5
              MaximumEventAgeInSeconds: 900
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AsgSchedulerFunction:
    Description: "AsgScheduler Function ARN"
    Value: !GetAtt AsgSchedulerFunction.Arn
  AsgSchedulerFunctionRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AsgSchedulerFunctionRole.Arn
